// <auto-generated />
namespace TicketsApi.EfData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _Create_Database : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_Create_Database));
        
        string IMigrationMetadata.Id
        {
            get { return "201601150011233__Create_Database"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
